version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python habit_tracker/manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    env_file: .env
    depends_on:
      - db
