# Generated by Django 5.0.6 on 2024-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name'], 'verbose_name': 'Habit', 'verbose_name_plural': 'Habits'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(),
        ),
    ]
