# Generated by Django 5.0.6 on 2024-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_alter_habit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
