# Generated by Django 5.0.6 on 2024-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_end_date_alter_habit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='required_count',
            field=models.IntegerField(default=0),
        ),
    ]
