# Generated by Django 5.0.6 on 2024-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_required_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='required_count',
            field=models.IntegerField(default=1),
        ),
    ]
