# Generated by Django 5.0.6 on 2024-06-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['time'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
    ]
